const db= require('../dbConnect')


module.exports={
    getHivOutreachDataToPrint:async (req,res)=>{
        let {id}=req.params
        const text=`
        select 
        events.id,
    events.eventDateCreated,
    events.programID,
    events.programName,
    events.eventName,
    events.eventDate,
    events.eventStartTime,
    events.eventFinishTime,
    events.healthAreaOfFocusID,
    events.healthAreaOfFocusName,
    events.createdByName,
    events.createdByLastname,
    events.eventZipCode,
    events.borough,
    events.oefEventEmail,
    events.deliveryPartner,
    events.locationAddress,
    events.onlineInPersonEventType,
    events.inPersonEventTypeName,
    events.inPersonEventTypeNameOther,
    events.inPersonEventTypeID,
    events.onlineEventTypeName,
    events.onlineEventTypeID,
    events.submissionstatus,
    events.onelinedescription,
    events.oefEventPresentationTopic,
    events.submissionNotes,
    events_output.isClusterEvent,
    events_output.cluster,
    events_output.clusterFbos,
    events_output.partnerOrganization1,
    events_output.partnerOrganization1Other,
    events_output.partnerOrganization2,
    events_output.nationalAwarenessDay,
    events_output.targetAudience,
    events_output.targetAudienceOther,
    events_output.totalTalkedHivPrepSaferSex,
    events_output.eventQuestions,
    events_output.eventHighlights,
    events_output.capacityTrainingUseful,
    events_output.lessonsLearned,
    events_output.nationalAwarenessDayOther,
    events_output.eventTypeName,
    events_output.zipCode,
    events_output.masks,
    events_output.covidLiterature,
    events_output.vaccineRelatedLiterature,
    events_output.hivLiterature,
    events_output.hepCLiterature,
    events_output.prepLiterature,
    events_output.saferSexKits,
    events_output.healthDisparitiesLiterature,
    events_output.bagsBoxesFood,
    events_output.handSanitizers,
    events_output.covidVaccineSiteReferralDetails,
    events_output.totalAttendees,
    events_output.eventChallenges,
    events_output.eventTestingDone,
    events_output.hivTesting,
    events_output.hepCTesting,
    events_output.covidTesting,
    events_output.otherTesting,
    events_output.hivTestingAgency,
    events_output.hivTestedTotal,
    events_output.hivReactiveResults,
    events_output.prepReferrals,
    events_output.hivLinkedToCare,
    events_output.hivServicesReferredTo,
    events_output.hivFemale,
    events_output.hivMale,
    events_output.hivTransgenderFemale,
    events_output.hivTransgenderMale,
    events_output.hivGenderNonConforming,
    events_output.hivNonBinary,
    events_output.hivOtherGenderIdentity,
    events_output.hivGenderDeclinedToAnswer,
    events_output.hivUnder15,
    events_output.hiv16_19,
    events_output.hiv20_24,
    events_output.hiv25_29,
    events_output.hiv30_34,
    events_output.hiv35_39,
    events_output.hiv40_44,
    events_output.hiv45_49,
    events_output.hiv50_54,
    events_output.hiv55_59,
    events_output.hiv60_64,
    events_output.hiv65_69,
    events_output.hiv70,
    events_output.hivAgeDeclinedToAnswer,
    events_output.hivBlackOrAfricanAmerican,
    events_output.hivHispanic,
    events_output.hivAsian,
    events_output.hivAmericanIndianOrAlaskaNative,
    events_output.hivMiddleEasternOrNorthAfrican,
    events_output.hivNativeHawaiianOrOtherPacificIslander,
    events_output.hivWhite,
    events_output.hivSomeOtherRace,
    events_output.hivRaceDeclinedToAnswer,
    events_output.hivNotHispanic,
    events_output.hivMexicanMexicanAmericanOrChicano,
    events_output.hivPuertoRican,
    events_output.hivCuban,
    events_output.hivDominican,
    events_output.hivEcuadorian,
    events_output.hivOtherHispanic,
    events_output.hivEthnicityDeclinedToAnswer,
    events_output.hivGayOrLesbian,
    events_output.hivStraightOrHeterosexual,
    events_output.hivBisexual,
    events_output.hivQueer,
    events_output.hivQuestioningOrNotSure,
    events_output.hivSexualOrientationUnknown,
    events_output.hivSexualOrientationDeclinedToAnswer,
    events_output.hepCTestingAgency,
    events_output.hepCTestedTotal,
    events_output.hepCReactiveResults,
    events_output.hepCLinkedToCare,
    events_output.hepCServicesReferredTo,
    events_output.hepCFemale,
    events_output.hepCMale,
    events_output.hepCTransgenderFemale,
    events_output.hepCTransgenderMale,
    events_output.hepCGenderNonConforming,
    events_output.hepCNonBinary,
    events_output.hepCOtherGenderIdentity,
    events_output.hepCGenderDeclinedToAnswer,
    events_output.hepCUnder15,
    events_output.hepC16_19,
    events_output.hepC20_24,
    events_output.hepC25_29,
    events_output.hepC30_34,
    events_output.hepC35_39,
    events_output.hepC40_44,
    events_output.hepC45_49,
    events_output.hepC50_54,
    events_output.hepC55_59,
    events_output.hepC60_64,
    events_output.hepC65_69,
    events_output.hepC70,
    events_output.hepCAgeDeclinedToAnswer,
    events_output.hepCBlackOrAfricanAmerican,
    events_output.hepCHispanic,
    events_output.hepCAsian,
    events_output.hepCAmericanIndianOrAlaskaNative,
    events_output.hepCMiddleEasternOrNorthAfrican,
    events_output.hepCNativeHawaiianOrOtherPacificIslander,
    events_output.hepCWhite,
    events_output.hepCSomeOtherRace,
    events_output.hepCRaceDeclinedToAnswer,
    events_output.hepCNotHispanic,
    events_output.hepCMexicanMexicanAmericanOrChicano,
    events_output.hepCPuertoRican,
    events_output.hepCCuban,
    events_output.hepCDominican,
    events_output.hepCEcuadorian,
    events_output.hepCOtherHispanic,
    events_output.hepCEthnicityDeclinedToAnswer,
    events_output.hepCGayOrLesbian,
    events_output.hepCStraightOrHeterosexual,
    events_output.hepCBisexual,
    events_output.hepCQueer,
    events_output.hepCQuestioningOrNotSure,
    events_output.hepCSexualOrientationUnknown,
    events_output.hepCSexualOrientationDeclinedToAnswer,
    events_output.otherTestingType,
    events_output.otherTestedTotal,
    events_output.hivGenderNotSureQuestioning,
    events_output.altAgeHivUnder13,
    events_output.altAgeHiv13_18,
    events_output.altAgeHiv19_24,
    events_output.hivMoreThanOneRace,
    events_output.hepCGenderNotSureQuestioning,
    events_output.altAgeHepCUnder13,
    events_output.altAgeHepC13_18,
    events_output.altAgeHepC19_24,
    events_output.hepCMoreThanOneRace,
    events_output.datePostEventSurvey,
    events_output.guestSpeakers,
    events_output.nameGuestSpeakers
 
        from events
        inner join events_output on  events.id =events_output.eventid
        where events.id=$1
        `
       const values=[id]
        try {
            const allData = await db.query(text,values);
            const response = allData.rows;
            res.send(response);
          } catch (e) {
            res.send("an error ocurred");
            console.log("error",e)
          }
    },
    getCabDataToPrint:async (req,res)=>{
        let {id}=req.params
        const text=`
        select
        events.id,
        events.eventDateCreated,
    events.programId,
    events.programName,
    events.eventDate,
    events.eventStartTime,
    events.eventFinishTime,
    events.healthAreaOfFocusId,
    events.healthAreaOfFocusName,
    events.createdByName,
    events.createdByLastname,
    events.oefEventEmail,
    events.deliveryPartner,
    events.submissionStatus,
    events.submissionNotes,
    events.eventRole,
    events.surveyName,
    events_output.cluster,
    events_output.clusterFbos,
    events_output.eventQuestions,
    events_output.eventHighlights,
    events_output.totalAttendees,
    events_output.eventID,
    events_output.eventDateCreated,
    events_output.programID,
    events_output.programName,
    events_output.eventName,
    events_output.eventDate,
    events_output.eventDateCreated,
    events_output.createdByName,
    events_output.createdbyLastName,
    events_output.oefEventEmail,
    events_output.eventRole,
    events_output.eventStartTime,
    events_output.eventFinishTime,
    events_output.deliveryPartner
    from events
    inner join events_output on  events.id =events_output.eventid
    where events.id=$1
        `
       const values=[id]
        try {
            const allData = await db.query(text,values);
            const response = allData.rows;
            res.send(response);
          } catch (e) {
            res.send("an error ocurred");
            console.log("error",e)
          }
    },
}